remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-minimal

title: Maximilian Weiß
logo: foto.jpg
description: I am a Postdoctoral Researcher at the University of Tuebingen. I am partly funded by the ERC Starting Grant AIRMAC (agreement ID 101114991). I work in the area of macroeconomics with heterogeneity, using structural models that relate macro- and micro-level data. I hold a PhD in Economics from the University of Bonn.
github: false
