remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-minimal

title: Maximilian Weiß
logo: foto.jpg
description: I am a Postdoctoral Researcher at the University of Tuebingen. In my research, I analyze macroeconomic questions connecting evidence on the aggregate level with micro-level data, using structural models. I also work on computational methods for heterogeneous agent models. I hold a PhD in Economics from the University of Bonn.
